"""Documentation integrity: relative links resolve, footnote keys are defined and used, generated files carry their header."""
import pathlib
import re
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import lint  # noqa: E402

DOCS = sorted((ROOT / "docs").glob("*.md")) + [ROOT / "README.md"]
REFERENCES = ROOT / "docs" / "references.md"
LINK = re.compile(r"\]\(([^)\s]+)\)")
FOOTNOTE_USE = re.compile(r"\[\^([\w-]+)\](?!:)")
FOOTNOTE_DEF = re.compile(r"^\[\^([\w-]+)\]:", re.M)
BACKTICK_KEY = re.compile(r"`([a-z][\w-]*)`")


FENCE = re.compile(r"```.*?```", re.S)
INLINE = re.compile(r"`[^`\n]*`")


def read(p: pathlib.Path) -> str:
    return p.read_text(encoding="utf-8") if p.exists() else ""


def prose(p: pathlib.Path) -> str:
    """Document text with fenced blocks and inline code removed, so `[^key]` examples are not counted as citations."""
    return INLINE.sub("", FENCE.sub("", read(p)))


class Links(unittest.TestCase):
    def test_relative_links_resolve(self):
        for doc in DOCS:
            if not doc.exists():
                continue
            text = read(doc)
            for target in LINK.findall(text):
                if target.startswith(("http://", "https://", "#", "mailto:")):
                    continue
                path = target.split("#", 1)[0]
                if not path:
                    continue
                resolved = (doc.parent / path).resolve()
                with self.subTest(doc=doc.name, link=target):
                    self.assertTrue(resolved.exists(), f"{doc.name}: broken link {target}")


class Footnotes(unittest.TestCase):
    def test_used_keys_are_defined(self):
        defined = set(FOOTNOTE_DEF.findall(read(REFERENCES)))
        self.assertTrue(defined, "docs/references.md defines no footnote keys")
        for doc in DOCS:
            for key in FOOTNOTE_USE.findall(prose(doc)):
                with self.subTest(doc=doc.name, key=key):
                    self.assertIn(key, defined)

    def test_defined_keys_are_used(self):
        defined = set(FOOTNOTE_DEF.findall(read(REFERENCES)))
        used = set()
        for doc in DOCS:
            if doc == REFERENCES:
                continue
            text = read(doc)
            used.update(FOOTNOTE_USE.findall(text))
            used.update(k for k in BACKTICK_KEY.findall(text) if k in defined)
        for spec in lint.CHECKS:
            used.update(spec.source)
        unused = defined - used
        self.assertEqual(unused, set(), f"reference keys never cited: {sorted(unused)}")

    def test_check_sources_are_defined(self):
        defined = set(FOOTNOTE_DEF.findall(read(REFERENCES)))
        for spec in lint.CHECKS:
            for key in spec.source:
                with self.subTest(check=spec.id, key=key):
                    self.assertIn(key, defined)


class Generated(unittest.TestCase):
    def test_generated_files_carry_header(self):
        for rel in ("docs/report.md", "docs/generated/summary.md"):
            p = ROOT / rel
            if not p.exists():
                continue
            self.assertIn("generated by scripts/report.py", read(p).splitlines()[0:4].__str__(), rel)


if __name__ == "__main__":
    unittest.main()
