#!/usr/bin/env python3
"""Generate docs/report.md, docs/generated/summary.md and the README summary block from results/v1/checks.csv.

Usage:
  python3 scripts/report.py           write the three outputs
  python3 scripts/report.py --check   exit 1 if regenerating would change any output

Tables are in manifest order. There is no rank column and no sorting by score anywhere in this file.
Contract: docs/design.md section 6.
"""
from __future__ import annotations

import argparse
import csv
import json
import statistics
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import lint  # noqa: E402

MANIFEST = ROOT / "data" / "manifest.toml"
LOCK = ROOT / "data" / "manifest.lock.json"
CHECKS_CSV = ROOT / "results" / "v1" / "checks.csv"
RUN_JSON = ROOT / "results" / "v1" / "run.json"
REPORT = ROOT / "docs" / "report.md"
SUMMARY = ROOT / "docs" / "generated" / "summary.md"
README = ROOT / "README.md"
MARK_START = "<!-- summary:start -->"
MARK_END = "<!-- summary:end -->"
GENERATED = "<!-- generated by scripts/report.py; do not edit -->"


def load() -> tuple[dict, dict, list[dict]]:
    with MANIFEST.open("rb") as fh:
        manifest = tomllib.load(fh)
    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    with CHECKS_CSV.open(encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    return manifest, lock, rows


def by_file(rows: list[dict]) -> dict[str, dict[str, dict]]:
    out: dict[str, dict[str, dict]] = defaultdict(dict)
    for r in rows:
        out[r["file"]][r["check_id"]] = r
    return out


def value(rows_of_file: dict[str, dict], check_id: str) -> float | None:
    v = rows_of_file.get(check_id, {}).get("value", "")
    return float(v) if v not in ("", None) else None


def score(rows_of_file: dict[str, dict]) -> tuple[int, int]:
    passed = applicable = 0
    for spec in lint.CHECKS:
        if spec.measure:
            continue
        r = rows_of_file.get(spec.id)
        if not r or r["applicable"] != "true":
            continue
        applicable += 1
        passed += 1 if r["pass"] == "true" else 0
    return passed, applicable


def fmt_stat(values: list[float]) -> str:
    if not values:
        return "–"
    return f"{statistics.median(values):.0f} ({min(values):.0f}–{max(values):.0f})"


def md_table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    for r in rows:
        lines.append("| " + " | ".join(r) + " |")
    return "\n".join(lines)


def build(manifest: dict, lock: dict, rows: list[dict]) -> tuple[str, str]:
    files = by_file(rows)
    entries = manifest.get("files", [])
    keys = [e["key"] for e in entries]
    types = {e["key"]: e["type"] for e in entries}
    checks = [c for c in lint.CHECKS if not c.measure]

    # --- corpus descriptives
    corpus_lines: list[list[str]] = []
    for t in ("project", "generic"):
        subset = [k for k in keys if types[k] == t]
        if not subset:
            continue
        corpus_lines.append([
            t, str(len(subset)),
            fmt_stat([value(files[k], "measure-lines") for k in subset]),
            fmt_stat([value(files[k], "measure-words") for k in subset]),
            fmt_stat([value(files[k], "measure-bytes") for k in subset]),
            fmt_stat([value(files[k], "measure-tokens-approx") for k in subset]),
            str(sum(1 for k in subset if (value(files[k], "measure-lines") or 0) <= 200)),
        ])
    corpus_lines.append([
        "all", str(len(keys)),
        fmt_stat([value(files[k], "measure-lines") for k in keys]),
        fmt_stat([value(files[k], "measure-words") for k in keys]),
        fmt_stat([value(files[k], "measure-bytes") for k in keys]),
        fmt_stat([value(files[k], "measure-tokens-approx") for k in keys]),
        str(sum(1 for k in keys if (value(files[k], "measure-lines") or 0) <= 200)),
    ])
    corpus_table = md_table(
        ["type", "files", "lines median (min–max)", "words", "bytes", "approx. tokens (chars/4)", "files ≤ 200 lines"],
        corpus_lines,
    )

    # --- catalog
    catalog_table = md_table(
        ["id", "rule", "applies to", "grade", "source"],
        [[f"`{c.id}`", c.description, c.applies_to, c.grade, ", ".join(f"[^{s}]" for s in c.source)] for c in checks],
    )

    # --- matrix
    def cell(r: dict | None) -> str:
        if not r or r["applicable"] != "true":
            return "n/a"
        return "pass" if r["pass"] == "true" else "fail"

    def matrix_row(key: str, label: str) -> list[str]:
        p, a = score(files[key])
        return [label, types.get(key, files[key].get("len-lines", {}).get("type", "")) or "", *[cell(files[key].get(c.id)) for c in checks], f"{p}/{a}"]

    header = ["file", "type", *[f"`{c.id}`" for c in checks], "score (passed/applicable)"]
    matrix_rows = [matrix_row(e["key"], f"{e['repo']} `{e['path']}`") for e in entries]
    matrix_table = md_table(header, matrix_rows)
    author_table = ""
    if "author" in files:
        author_row = matrix_row("author", f"`{manifest['author']['path']}`")
        author_row[1] = files["author"].get("cmd-test", {}).get("applicable") == "true" and "project" or "generic"
        author_table = md_table(header, [author_row])

    # --- pass rate by type
    def rate(subset: list[str], check_id: str) -> str:
        app = [k for k in subset if files[k].get(check_id, {}).get("applicable") == "true"]
        if not app:
            return "–"
        ok = sum(1 for k in app if files[k][check_id]["pass"] == "true")
        return f"{100 * ok / len(app):.0f}% ({ok}/{len(app)})"

    proj = [k for k in keys if types[k] == "project"]
    gen = [k for k in keys if types[k] == "generic"]
    rate_table = md_table(
        ["check", "project files", "generic files", "all"],
        [[f"`{c.id}`", rate(proj, c.id), rate(gen, c.id), rate(keys, c.id)] for c in checks],
    )

    def mean_score(subset: list[str]) -> str:
        if not subset:
            return "–"
        vals = []
        for k in subset:
            p, a = score(files[k])
            if a:
                vals.append(p / a)
        return f"{100 * statistics.mean(vals):.0f}%" if vals else "–"

    run = json.loads(RUN_JSON.read_text(encoding="utf-8")) if RUN_JSON.exists() else {}
    summary_lines = [
        GENERATED,
        f"- Results version: `{run.get('results_version', 'v1')}` · corpus snapshot lock `{run.get('lock_sha256', '')[:12]}`",
        f"- Corpus: {len(keys)} files ({len(proj)} project, {len(gen)} generic); the author's file is reported separately",
        f"- Checks: {len(checks)} deterministic checks, all grade `G` (guidance-only) until experiments run",
        f"- Mean guideline-conformance score, project files: {mean_score(proj)}",
        f"- Mean guideline-conformance score, generic files: {mean_score(gen)}",
    ]
    summary = "\n".join(summary_lines) + "\n"

    report = f"""---
title: Report
---
{GENERATED}

# Report (results v1)

The score in every table below is **guideline conformance**: the share of applicable deterministic checks a file passes. Each check cites vendor guidance or literature (grade `G`); none is yet backed by an experiment in this repository. A high score does not mean the file makes an agent better, and no table here ranks files. See [limitations](limitations.md) before quoting any number.

## 1. Corpus

{corpus_table}

Lines, words, bytes and approximate tokens are medians with min–max in parentheses. Approximate tokens are characters divided by four, not a tokenizer.

## 2. Check catalog

{catalog_table}

Measurement checks (`measure-*`) feed table 1 and are not scored.

## 3. Check matrix

Rows are in manifest order. `n/a` means the check does not apply to that file's type or filename.

{matrix_table}

### Author's file (not part of the corpus)

{author_table}

## 4. Pass rate by type

{rate_table}

Files are typed `project` when they contain a runnable command and `generic` otherwise; the four `cmd-*` checks apply only to project files. Percentages are over applicable files.

## References

See [references.md](references.md) for every key cited in table 2.
"""
    return report, summary


def splice_readme(readme: str, summary: str) -> str:
    start = readme.find(MARK_START)
    end = readme.find(MARK_END)
    if start == -1 or end == -1 or end < start:
        raise SystemExit("report: README.md is missing the summary markers")
    body = "\n".join(l for l in summary.splitlines() if l != GENERATED)
    return readme[: start + len(MARK_START)] + "\n" + body + "\n" + readme[end:]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if regeneration would change any output")
    args = ap.parse_args(argv)
    manifest, lock, rows = load()
    report, summary = build(manifest, lock, rows)
    readme_old = README.read_text(encoding="utf-8") if README.exists() else None
    readme_new = splice_readme(readme_old, summary) if readme_old is not None else None
    outputs = [(REPORT, report), (SUMMARY, summary)]
    if readme_new is not None:
        outputs.append((README, readme_new))
    if args.check:
        stale = [p for p, content in outputs if not p.exists() or p.read_text(encoding="utf-8") != content]
        for p in stale:
            print(f"report --check: {p.relative_to(ROOT)} is stale; run `make report`")
        return 1 if stale else 0
    for p, content in outputs:
        p.parent.mkdir(parents=True, exist_ok=True)
        if not p.exists() or p.read_text(encoding="utf-8") != content:
            p.write_text(content, encoding="utf-8")
            print(f"report: wrote {p.relative_to(ROOT)}")
        else:
            print(f"report: {p.relative_to(ROOT)} unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
